from enum import StrEnum, auto

#The idea would be that we could use these keys in the code with dot notation which then map into localizations that are stored in a json file as key-value pairs. A different file could be loaded for a different language
class LocalizationKeys(StrEnum):
    no_courses_found = auto(),
    password_mismatch = auto(),
    username_taken = auto(),
    user_does_not_exist = auto(),
    wrong_username_or_password = auto(),
    return_to_index_button = auto(),
    modify_button = auto(),
    delete_button = auto(),
    round_item_start = auto(),
    round_item_place = auto(),
    round_item_creator = auto(),
    round_item_players = auto(),
    create_course_button = auto(),
    browse_courses_button = auto(),
    create_round_button = auto(),
    find_round_button = auto(),
    log_out_button = auto(),
    log_in_button = auto(),
    register_button = auto()
    account_name_header = auto(),
    password_header = auto(),
    repeat_password_header = auto(),
    amount_players_header = auto(),
    start_time_header = auto(),
    select_course_header = auto(),
    course_select_default = auto(),
    par_header = auto(),
    hole_length_header = auto(),
    course_type_header = auto(),
    course_difficulty_header = auto(),
    course_type_default = auto(),
    course_diff_default = auto(),
    course_holes_header = auto(),
    course_name_header = auto()
