#The idea would be that these localizations could be loaded for example from a json file. For now just a dict.

localizations_fin = {
    "main_header": "Frisbeegolflaskuri",
    "register_header": "Rekisteröityminen",
    "log_in_header": "Kirjautuminen",
    "account_name_header": "Tunnus:",
    "username_header": "Käyttäjänimi:",
    "user_id_header": "Käyttäjän ID:",
    "password_header": "Salasana:",
    "repeat_password_header": "Salasana uudestaan:",
    "user_page_header": "Käyttäjäsivu",
    "new_course_header": "Uusi rata",
    "new_round_header": "Uusi kierros",
    "create_course_button": "Lisää rata",
    "browse_courses_button": "Selaa ratoja",
    "create_round_button": "Lisää kierros",
    "find_round_button":"Etsi kierros",
    "all_rounds_header":"Kierrokset",
    "delete_course_header": "Poista rata",
    "delete_course_are_you_sure": "Haluatko varmasti poistaa tämän radan?",
    "delete_course_button": "Poista rata",
    "delete_round_header": "Poista kierros",
    "delete_round_are_you_sure": "Haluatko varmasti poistaa tämän kierroksen?",
    "delete_round_button": "Poista kierros",
    "modify_round_header":"Muokkaa kierrosta",
    "find_round_header":"Etsi kierros",
    "find_by_course_name_header":"Etsi radan nimellä:",
    "find_by_date_header":"Etsi päivämäärällä:",
    "search_results_header":"Tulokset",
    "course_name_header": "Nimi:",
    "course_holes_header": "Väylien lukumäärä:",
    "add_holes_header": "Lisää väylien tiedot",
    "modify_num_holes_header": "Muokkaa väylien lukumäärää",
    "modify_holes_header": "Muokkaa väylien tietoja",
    "courses_header": "Radat",
    "course_information_header": "Väylien tiedot",
    "round_information_header": "Kierroksen tiedot",
    "user_amount_rounds_created": "Käyttäjällä on yhteensä {} luotua kierrosta",
    "rounds_created_by_user_header": "Käyttäjän lisäämät kierrokset:",
    "hole_header": "Väylä {}:",
    "par_header": "Par:",
    "hole_length_header": "Pituus (m):",
    "select_course_header": "Valitse rata:",
    "start_time_header": "Aloitusaika:",
    "amount_players_header": "Pelaajien määrä:",
    "course_select_default": "--Valitse rata--",
    "course_difficulty_header": "Radan vaikeustaso:",
    "course_difficulty": "Vaikeustaso",
    "course_diff_default": "--Valitse vaikeusluokitus--",
    "course_diff_easy": "Helppo",
    "course_diff_mod": "Haastava",
    "course_diff_hard": "Vaikea",
    "course_type_header": "Radan tyyppi:",
    "course_type": "Tyyppi",
    "course_type_default": "--Valitse radan tyyppi--",
    "course_type_open": "Avoin",
    "course_type_mixed": "Vaihteleva",
    "course_type_woods": "Metsä",
    "course_item_num_holes": "Väyliä:",
    "round_item_start": "Aloitusaika:",
    "round_item_place": "Paikka:",
    "round_item_creator": "Lisännyt:",
    "round_item_players": "Pelaajia:",
    "round_item_players_participating": "Ilmoittautuneita pelaajia:",
    "logged_in": "Olet kirjautunut nimellä",
    "registered_message": "Tunnus luotu",
    "register_button": "Luo tunnus",
    "log_in_button": "Kirjaudu sisään",
    "log_out_button": "Kirjaudu ulos",
    "next_button": "Seuraava",
    "modify_button": "Muokkaa",
    "delete_button": "Poista",
    "submit_changes_button": "Tallenna muutokset",
    "submit_search_button": "Lähetä",
    "to_hole_modification_button": "Muokkaa väyliä",
    "return_button": "Palaa takaisin",
    "return_to_index_button": "Palaa takaisin etusivulle",
    "return_to_courses_button": "Palaa ratalistaukseen",
    "str_no_courses_found": "VIRHE: ei ratoja tietokannassa. Luo rata luodaksesi kierroksen."
}

localizations = localizations_fin

def get_localization(key):
    s = str(key)
    if s in localizations:
        return localizations[s]
    else:
        print(f"Virhe: lokalisaatioavainta {s} ei löydy lokalisaatiotiedostosta.")