# Exclude a variety of commonly ignored directories.
exclude = [
    ".git",
    ".git-rewrite",
    ".pyenv",
    ".ruff_cache",
    ".venv",
    ".vscode",
    ".db",
    "__pypackages__",
    "venv",
    "pylintrc",
]

line-length = 120
indent-width = 4

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"